---
title: "Enquête sur le point de confort des personnes non-binaires"
author: "Maxence R. Ouafik"
date: "10/10/2020"
output: 
  bookdown::html_document2: default

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, widgetframe_widgets_dir = "./output")
library(scales)
```




```{r Data Preparation, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}

# En premier lieu : lire le fichier CSV généré par le Google Forms afin d'obtenir Survey_Data
source("./scripts/read_data.R", local = knitr::knit_global())

# Ensuite créer Survey_Data_AFAB à partir des données brutes. D'une part, les données sont transformées pour que chaque variable soit individualisées avec un 0 si la personne n'a pas coché la réponse et un 1, si la personne l'a cochée. 

source("./scripts/create_Survey_Data_AFAB.R", local = knitr::knit_global(), encoding = "UTF-8")

# Pareil pour les réponses des personnes NB AMAB

source("./scripts/create_Survey_Data_AMAB.R", local = knitr::knit_global(), encoding = "UTF-8")

#Ensuite, on crée un tableau résumant les réponses de la première question destinée aux personnes AFAB (nombre de personnes ayant répondu et pourcentage) Ce tableau nous servira à créer les graphiques. 

source("./scripts/create_AFAB_Conf_Sum.R", local = knitr::knit_global(), encoding = "UTF-8")

# Pareil pour la 2ème question

source("./scripts/create_AFAB_Inconf_Sum.R", local = knitr::knit_global(), encoding = "UTF-8")

# On s'occupe maintenant des mêmes étapes pour les personnes AMAB

source("./scripts/create_AMAB_Conf_Sum.R", local = knitr::knit_global(), encoding = "UTF-8")
source("./scripts/create_AMAB_Inconf_Sum.R", local = knitr::knit_global(), encoding = "UTF-8")



```

A l'heure actuelle, `r nrow(Survey_Data)` personnes ont répondu dont `r nrow(Survey_Data_AFAB)` (`r label_percent()((nrow(Survey_Data_AFAB)/nrow(Survey_Data)))`) personnes non-binaires assignées femmes à la naissance (AFAB) et `r nrow(Survey_Data_AMAB)` (`r label_percent()((nrow(Survey_Data_AMAB)/nrow(Survey_Data)))`) personnes non-binaires assignées hommes à la naissance (AMAB). 


```{r AFABConfPlot, echo=FALSE}

source("./scripts/create_AFAB_Conf_Plotly.R", local = knitr::knit_global(), encoding = "UTF-8")
```

  <figure><iframe src= "https://asrahal.github.io/Non_Binary_Survey/output/afab-conf.html" width="100%" height="600" <="" iframe"=""></iframe></figure>

<br>

```{r AFABInconfPlot, fig.cap = "Effets indésirables d'une THS pour les personnes NB AFAB", echo=FALSE}

source("./scripts/create_AFAB_Inconf_Plotly.R", local = knitr::knit_global(), encoding = "UTF-8")


```


  <figure><iframe src= "https://asrahal.github.io/Non_Binary_Survey/output/afab-inconf.html" width="100%" height="600" <="" iframe"=""></iframe></figure>

<br>

```{r AMABConfPlot, fig.cap = "Effets attendus d'une THS pour les personnes NB AMAB", echo=FALSE}

source("./scripts/create_AMAB_Conf_Plotly.R", local = knitr::knit_global(), encoding = "UTF-8")


```

<figure><iframe src= "https://asrahal.github.io/Non_Binary_Survey/output/amab-conf.html" width="100%" height="600" <="" iframe"=""></iframe></figure>

<br>

```{r AMABInconfPlot, fig.cap = "Effets indésirables d'une THS pour les personnes NB AMAB", echo=FALSE}

source("./scripts/create_AMAB_Inconf_Plotly.R", local = knitr::knit_global(), encoding = "UTF-8")


```

<figure><iframe src= "https://asrahal.github.io/Non_Binary_Survey/output/amab-inconf.html" width="100%" height="600" <="" iframe"=""></iframe></figure>

<br>

```{r message=FALSE, warning=FALSE}

# On commence par créer la liste des connexions pour le réseau AFAB
source("./scripts/create_Edgelist_AFAB.R", local = knitr::knit_global(), encoding = "UTF-8")

# Puis les noeuds pour le même réseau
source("./scripts/create_AFAB_Nodes.R", local = knitr::knit_global(), encoding = "UTF-8")

# On transforme la liste des connexions créée plus haut en une edgelist avec les ID des connexions et le poids de chaque ocnnexion
source("./scripts/create_AFAB_Edges.R", local = knitr::knit_global(), encoding = "UTF-8")

# Et maintenant on crée le graphique

library(tidygraph)
library(GGally)
library(RColorBrewer)
library(ggraph)
AFAB_Network <- tbl_graph(nodes = AFAB_Nodes, edges = AFAB_Edges, directed = FALSE) %>%
  mutate(Closeness = centrality_closeness(), Betweenness = centrality_betweenness(), Degree = centrality_degree(weight=weight))

set.seed(3952)
AFAB_Network_Plot <- ggnet2(AFAB_Network, mode = "fruchtermanreingold", node.size = "personnes", node.color = "category", palette = "Set2", edge.color = c("color", "lightgray"), edge.alpha = 0.5, label = "id", edge.size = AFAB_Edges$weight/50, text = paste( AFAB_Network$label)) +
  ggtitle("Réseau des attentes et craintes liées au THS chez les personnes NB AFAB") 
ggplotly(AFAB_Network_Plot) %>%
  layout(showlegend = FALSE, xaxis = ax, yaxis = ax)



```


```{r eval=FALSE, include=FALSE}

source("./scripts/edit_WP_post.R", local = knitr::knit_global(), encoding = "UTF-8")
```


