AMAB_Combined <- Survey_Data_AMAB %>%
  transmute(Breast = ifelse(Breast_Inconf == 1, 1, 
                            ifelse(Breast_Conf == 0 & Breast_Inconf == 0, 2, 
                                   ifelse(Breast_Conf == 1, 3, NA ))),
            Skin = ifelse(Skin_Inconf == 1, 1, 
                          ifelse(Skin_Conf == 0 & Skin_Inconf == 0, 2, 
                                 ifelse(Skin_Conf == 1, 3, NA ))),
            Erection = ifelse(Erection_Inconf == 1, 1, 
                              ifelse(Erection_Conf == 0 & Erection_Inconf == 0, 2, 
                                     ifelse(Erection_Conf == 1, 3, NA ))),
            Testes = ifelse(Testes_Inconf == 1, 1, 
                            ifelse(Testes_Conf == 0 & Testes_Inconf == 0, 2, 
                                   ifelse(Testes_Conf == 1, 3, NA ))),
            Fat = ifelse(Body_Fat_Inconf == 1, 1, 
                         ifelse(Body_Fat_Conf == 0 & Body_Fat_Inconf == 0, 2, 
                                ifelse(Body_Fat_Conf == 1, 3, NA ))),
            Facial_Hair = ifelse(Facial_Hair_Inconf == 1, 1, 
                                 ifelse(Facial_Hair_Conf == 0 & Facial_Hair_Inconf == 0, 2, 
                                        ifelse(Facial_Hair_Conf == 1, 3, NA ))),
            Body_Hair = ifelse(Body_Hair_Inconf == 1, 1, 
                               ifelse(Body_Hair_Conf == 0 & Body_Hair_Inconf == 0, 2, 
                                      ifelse(Body_Hair_Conf == 1, 3, NA ))),
            Muscle = ifelse(Muscle_Inconf == 1, 1, 
                            ifelse(Muscle_Conf == 0 & Muscle_Inconf == 0, 2, 
                                   ifelse(Muscle_Conf == 1, 3, NA ))))